set_languages("cxx20")
add_includedirs("c:/dev/vs2022/include")
target("osgl3")
    set_kind("binary")
    add_defines("WIN32")
    add_links("osg", "osgText", "osgDB", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
	add_linkdirs("c:/dev/vs2022/lib")
    add_files("osgsimplegl3.cpp", "info_visitor.cpp")
