set_project("osgearth-ck")                          
set_version("0.0.1", {build = "%Y%m%d%H%M"})
add_includedirs("c:/tools/vs2019/include")
add_linkdirs("c:/tools/vs2019/lib")
set_languages("cxx14")
target("oeck")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/osgearth_viewer.cpp", "src/panorama.cpp", "src/panorama_camera.cpp")
	add_files("src/pick.cpp", "src/angle_site.cpp")
    add_installfiles("earthfile/simple.earth", {prefixdir = "bin"})

target("light")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/light.cpp")

target("hud")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/hud.cpp")
--[[    
target("model")
    set_kind("binary")
    add_includedirs("c:/tools/vs2019/include")
    add_linkdirs("c:/tools/vs2019/lib")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/model.cpp")
    add_installfiles("earthfile/simple.earth", {prefixdir = "bin"})
--]]
target("quad")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/rect.cpp")
--[[
target("elev")
    set_kind("binary")
    add_includedirs("c:/tools/vs2019/include")
    add_linkdirs("c:/tools/vs2019/lib")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/elevation.cpp", "src/MouseHandler.cpp")
    add_installfiles("earthfile/simple.earth", {prefixdir = "bin"})
--]]	
target("ctrl")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
	add_includedirs("src")
    add_files("src/ctrl.cpp")
    add_installfiles("earthfile/simple.earth", {prefixdir = "bin"})

target("tex")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer")
    add_defines("WIN32")
    add_files("src/tex.cpp")
	
target("cone")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer")
    add_defines("WIN32")
    add_files("src/cone.cpp")

target("drag")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgManipulator", "OpenThreads")
    add_links("osgGA", "osgViewer")
    add_defines("WIN32")
    add_files("src/drag.cpp")

target("annotation")
    set_kind("binary")
    add_links("osg", "osgEarth", "osgText", "osgDB", "osgManipulator", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/annotation.cpp")

target("qt")
    add_rules("qt.widgetapp")
    add_frameworks("QtOpenGL")
    add_links("osg", "osgText", "osgDB", "osgManipulator", "OpenThreads", "osgQOpenGL")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_files("src/osg_widget.h")
    add_files("src/osg_widget.cpp", "src/osgviewerQt.cpp")

target("more_points")
    set_kind("binary")
    add_links("osg", "osgText", "osgDB", "osgEarth", "OpenThreads")
    add_links("osgGA", "osgViewer", "osgUtil")
    add_defines("WIN32")
    add_files("src/more_points.cpp")

target("gdalw")
    set_kind("binary")
    add_cxflags("/utf-8")
    add_links("gdal_i", "geos_c", "geos", "proj")
    add_files("src/g.cpp")
